import {isCookAvailable} from './domain.mjs';

const DEFAULT_CATEGORIES = ['Завтрак','Основное','Гарниры','Салаты','Закуски','Десерт','Напитки','Макдональдс','Булочная Вольчека'];

export function registerFeatures({app,db,auth,one,q,transaction,telegram}) {
  const column=(table,name,definition)=>{if(!q(`PRAGMA table_info(${table})`).some(c=>c.name===name))db.exec(`ALTER TABLE ${table} ADD COLUMN ${name} ${definition}`)};
  column('order_items','quantity','INTEGER NOT NULL DEFAULT 1');
  db.exec(`
    CREATE TABLE IF NOT EXISTS favorites(user_id INTEGER NOT NULL,dish_id INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,dish_id));
    CREATE TABLE IF NOT EXISTS categories(id INTEGER PRIMARY KEY,name TEXT NOT NULL UNIQUE,position INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY,user_id INTEGER NOT NULL,section TEXT NOT NULL,ref_id INTEGER,message TEXT NOT NULL,read_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS replacements(id INTEGER PRIMARY KEY,order_item_id INTEGER NOT NULL,proposed_dish_id INTEGER NOT NULL,price TEXT NOT NULL,variant TEXT,reason TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
    CREATE INDEX IF NOT EXISTS idx_orders_customer_created ON orders(customer_id,created_at);
    CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
    CREATE INDEX IF NOT EXISTS idx_order_items_cook_status ON order_items(cook_id,status);
    CREATE INDEX IF NOT EXISTS idx_cooks_user_dish ON cooks(user_id,dish_id);
    CREATE INDEX IF NOT EXISTS idx_reviews_dish_cook ON reviews(dish_id,cook_id);
    CREATE INDEX IF NOT EXISTS idx_ledger_debtor ON ledger(debtor_id,confirmed);
    CREATE INDEX IF NOT EXISTS idx_ledger_creditor ON ledger(creditor_id,confirmed);
    CREATE INDEX IF NOT EXISTS idx_notifications_unread ON notifications(user_id,read_at,section,id);
    CREATE INDEX IF NOT EXISTS idx_replacements_item ON replacements(order_item_id,id);
  `);
  const insertCategory=db.prepare('INSERT OR IGNORE INTO categories(name,position) VALUES(?,?)');
  DEFAULT_CATEGORIES.forEach((name,position)=>insertCategory.run(name,position));
  db.exec('PRAGMA optimize');

  const clients=new Map();
  const emit=(userIds,type='update')=>{for(const userId of new Set(userIds.filter(Boolean))){for(const res of clients.get(Number(userId))||[])res.write(`event: ${type}\ndata: ${JSON.stringify({type,at:Date.now()})}\n\n`)}};
  const notify=(userId,section,message,refId=null)=>{db.prepare('INSERT INTO notifications(user_id,section,ref_id,message) VALUES(?,?,?,?)').run(userId,section,refId,message);emit([userId],'update')};
  app.locals.emitUpdate=emit;
  app.locals.notify=notify;

  app.get('/api/events',(req,res)=>{const token=String(req.query.token||'');const user=one("SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires>datetime('now')",token);if(!user)return res.sendStatus(401);res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});res.flushHeaders();const set=clients.get(user.id)||new Set();set.add(res);clients.set(user.id,set);res.write(`event: ready\ndata: ${JSON.stringify({type:'ready'})}\n\n`);const heartbeat=setInterval(()=>res.write(': keep-alive\n\n'),20000);req.on('close',()=>{clearInterval(heartbeat);set.delete(res);if(!set.size)clients.delete(user.id)})});

  const parse=(row,keys)=>{for(const key of keys)if(row?.[key])try{row[key]=JSON.parse(row[key])}catch{}return row};
  app.get('/api/bootstrap',auth,(req,res)=>{
    const dishes=q(`SELECT d.*,json_group_array(json_object('id',c.id,'user_id',c.user_id,'name',u.name,'price',c.price,'availability',c.availability,'availability_note',c.availability_note,'minutes',c.minutes,'note',c.note,'addons',c.addons,'variants',c.variants)) cooks FROM dishes d JOIN cooks c ON c.dish_id=d.id JOIN users u ON u.id=c.user_id WHERE d.archived=0 GROUP BY d.id ORDER BY d.created_at DESC`).map(d=>{d.cooks=JSON.parse(d.cooks).map(c=>parse(c,['price','addons','variants']));return d});
    const orders=q(`SELECT oi.*,o.customer_id,o.scheduled_at,o.created_at order_created,d.title,d.image dish_image,o.comment order_comment,u.name cook_name FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN dishes d ON d.id=oi.dish_id JOIN users u ON u.id=oi.cook_id WHERE o.deleted=0 AND (o.customer_id=? OR oi.cook_id=?) ORDER BY oi.id DESC`,req.user.id,req.user.id).map(x=>parse(x,['price','addons','variant']));
    const ledger=q(`SELECT l.*,c.emoji,c.name_one,c.name_few,c.name_many,du.name debtor,cr.name creditor FROM ledger l JOIN currencies c ON c.id=l.currency_id JOIN users du ON du.id=l.debtor_id JOIN users cr ON cr.id=l.creditor_id WHERE debtor_id=? OR creditor_id=? ORDER BY l.id DESC`,req.user.id,req.user.id);
    const reviews=q('SELECT r.*,u.name author_name FROM reviews r JOIN users u ON u.id=r.author_id ORDER BY r.created_at DESC');
    const replacements=q(`SELECT r.*,d.title proposed_title,d.image proposed_image FROM replacements r JOIN order_items oi ON oi.id=r.order_item_id JOIN orders o ON o.id=oi.order_id JOIN dishes d ON d.id=r.proposed_dish_id WHERE o.deleted=0 AND (o.customer_id=? OR oi.cook_id=?) ORDER BY r.id DESC`,req.user.id,req.user.id).map(x=>parse(x,['price','variant']));
    const notificationCounts={orders:0,debts:0,reviews:0};for(const row of q('SELECT section,count(*) count FROM notifications WHERE user_id=? AND read_at IS NULL GROUP BY section',req.user.id))notificationCounts[row.section]=row.count;
    const popular=Object.fromEntries(q("SELECT dish_id,count(*) count FROM order_items WHERE status='выполнен' GROUP BY dish_id").map(x=>[x.dish_id,x.count]));
    const stats={ordered:one("SELECT count(DISTINCT o.id) count FROM orders o WHERE o.customer_id=? AND o.deleted=0",req.user.id)?.count||0,cooked:one("SELECT count(*) count FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.cook_id=? AND oi.status='выполнен' AND o.deleted=0",req.user.id)?.count||0,average:Number(one('SELECT round(avg(rating),1) value FROM reviews WHERE cook_id=?',req.user.id)?.value||0),reviews:one('SELECT count(*) count FROM reviews WHERE cook_id=?',req.user.id)?.count||0,topDishes:q("SELECT d.title,count(*) count FROM order_items oi JOIN dishes d ON d.id=oi.dish_id JOIN orders o ON o.id=oi.order_id WHERE oi.cook_id=? AND oi.status='выполнен' AND o.deleted=0 GROUP BY oi.dish_id ORDER BY count(*) DESC,d.title LIMIT 5",req.user.id)};
    res.json({users:q('SELECT id,name,avatar FROM users'),currencies:q('SELECT * FROM currencies ORDER BY id'),categories:q('SELECT * FROM categories ORDER BY position,id'),fridge:q('SELECT * FROM fridge ORDER BY name'),dishes,orders,ledger,reviews,replacements,favoriteIds:q('SELECT dish_id FROM favorites WHERE user_id=?',req.user.id).map(x=>x.dish_id),notificationCounts,popular,stats});
  });

  app.post('/api/notifications/read',auth,(req,res)=>{const section=String(req.body.section||'');if(section)db.prepare("UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE user_id=? AND section=? AND read_at IS NULL").run(req.user.id,section);else db.prepare("UPDATE notifications SET read_at=CURRENT_TIMESTAMP WHERE user_id=? AND read_at IS NULL").run(req.user.id);emit([req.user.id]);res.json({ok:true})});
  app.put('/api/favorites/:dishId',auth,(req,res)=>{if(!one('SELECT id FROM dishes WHERE id=? AND archived=0',req.params.dishId))return res.status(404).json({error:'Блюдо не найдено'});if(req.body.active)db.prepare('INSERT OR IGNORE INTO favorites(user_id,dish_id) VALUES(?,?)').run(req.user.id,req.params.dishId);else db.prepare('DELETE FROM favorites WHERE user_id=? AND dish_id=?').run(req.user.id,req.params.dishId);emit([req.user.id]);res.json({ok:true})});

  app.post('/api/categories',auth,(req,res)=>{const name=String(req.body.name||'').trim().slice(0,50);if(!name)return res.status(400).json({error:'Введите название категории'});try{const result=db.prepare('INSERT INTO categories(name,position) VALUES(?,COALESCE((SELECT max(position)+1 FROM categories),0))').run(name);emit([1,2]);res.json({id:Number(result.lastInsertRowid)})}catch{return res.status(400).json({error:'Такая категория уже есть'})}});
  app.put('/api/categories/:id',auth,(req,res)=>{const current=one('SELECT * FROM categories WHERE id=?',req.params.id);if(!current)return res.status(404).json({error:'Категория не найдена'});const name=String(req.body.name??current.name).trim().slice(0,50);if(!name)return res.status(400).json({error:'Введите название категории'});try{transaction(()=>{db.prepare('UPDATE categories SET name=?,position=?,active=? WHERE id=?').run(name,Number.isInteger(req.body.position)?req.body.position:current.position,req.body.active===undefined?current.active:(req.body.active?1:0),current.id);if(name!==current.name)db.prepare('UPDATE dishes SET category=? WHERE category=?').run(name,current.name)});emit([1,2]);res.json({ok:true})}catch{return res.status(400).json({error:'Такая категория уже есть'})}});
  app.delete('/api/categories/:id',auth,(req,res)=>{const category=one('SELECT * FROM categories WHERE id=?',req.params.id);if(!category)return res.status(404).json({error:'Категория не найдена'});if(one('SELECT id FROM dishes WHERE category=? AND archived=0 LIMIT 1',category.name))return res.status(400).json({error:'Сначала перенесите блюда из этой категории'});db.prepare('UPDATE categories SET active=0 WHERE id=?').run(category.id);emit([1,2]);res.json({ok:true})});

  const pickPrice=(cook,variantId)=>{const variants=JSON.parse(cook.variants||'[]');const variant=variants.find(v=>String(v.id)===String(variantId));if(variants.length&&!variant)throw Error('Выберите доступную вариацию');return {price:variant?.price||JSON.parse(cook.price||'[]'),variant:variant?{id:variant.id,name:variant.name,price:variant.price}:null}};
  app.post('/api/orders/:id/repeat',auth,async(req,res)=>{const source=one('SELECT * FROM orders WHERE id=? AND customer_id=? AND deleted=0',req.params.id,req.user.id);if(!source)return res.status(404).json({error:'Заказ не найден'});try{const items=q('SELECT * FROM order_items WHERE order_id=?',source.id);if(!items.length)throw Error('В заказе нет блюд');const targets=new Set();const id=transaction(()=>{const order=db.prepare("INSERT INTO orders(customer_id,scheduled_at,comment) VALUES(?,NULL,?)").run(req.user.id,'Повтор заказа №'+source.id);for(const old of items){const cook=one('SELECT * FROM cooks WHERE dish_id=? AND user_id=?',old.dish_id,old.cook_id);if(!cook||!isCookAvailable(cook))throw Error('Одно из блюд сейчас недоступно');const oldVariant=parse({...old},['variant']).variant;const selected=pickPrice(cook,oldVariant?.id);const availableAddons=JSON.parse(cook.addons||'[]');const oldAddons=JSON.parse(old.addons||'[]');const addons=availableAddons.filter(a=>oldAddons.some(x=>String(x.id)===String(a.id)));db.prepare('INSERT INTO order_items(order_id,dish_id,cook_id,price,addons,comment,variant,quantity) VALUES(?,?,?,?,?,?,?,?)').run(order.lastInsertRowid,old.dish_id,old.cook_id,JSON.stringify(selected.price),JSON.stringify(addons),old.comment||'',selected.variant?JSON.stringify(selected.variant):null,Math.max(1,old.quantity||1));targets.add(old.cook_id)}return Number(order.lastInsertRowid)});for(const cookId of targets){notify(cookId,'orders','Новый повторный заказ',id);const chat=one('SELECT telegram_chat FROM users WHERE id=?',cookId)?.telegram_chat;void telegram(chat,'🍽 Новый заказ от '+req.user.name)}emit([req.user.id]);res.json({id})}catch(error){res.status(400).json({error:error.message})}});

  app.post('/api/order-items/:id/replacement',auth,(req,res)=>{const item=one('SELECT oi.*,o.customer_id FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.id=? AND o.deleted=0',req.params.id);if(!item||item.cook_id!==req.user.id)return res.status(403).json({error:'Предложить замену может повар'});if(['выполнен','отклонён','отменён'].includes(item.status))return res.status(400).json({error:'Заказ уже завершён'});const dishId=Number(req.body.dish_id),cook=one('SELECT * FROM cooks WHERE dish_id=? AND user_id=?',dishId,req.user.id);if(!cook||!isCookAvailable(cook))return res.status(400).json({error:'Выберите доступное блюдо, которое вы готовите'});const reason=String(req.body.reason||'').trim().slice(0,500);if(!reason)return res.status(400).json({error:'Напишите причину замены'});try{const selected=pickPrice(cook,req.body.variantId);const id=transaction(()=>{db.prepare("UPDATE replacements SET status='rejected' WHERE order_item_id=? AND status='pending'").run(item.id);return Number(db.prepare('INSERT INTO replacements(order_item_id,proposed_dish_id,price,variant,reason) VALUES(?,?,?,?,?)').run(item.id,dishId,JSON.stringify(selected.price),selected.variant?JSON.stringify(selected.variant):null,reason).lastInsertRowid)});notify(item.customer_id,'orders','Повар предложил замену блюда',item.id);res.json({id})}catch(error){res.status(400).json({error:error.message})}});
  app.post('/api/replacements/:id/respond',auth,(req,res)=>{const replacement=one('SELECT r.*,oi.cook_id,o.customer_id FROM replacements r JOIN order_items oi ON oi.id=r.order_item_id JOIN orders o ON o.id=oi.order_id WHERE r.id=?',req.params.id);if(!replacement||replacement.customer_id!==req.user.id)return res.status(403).json({error:'Ответить может заказчик'});if(replacement.status!=='pending')return res.status(400).json({error:'На это предложение уже ответили'});const accept=!!req.body.accept;transaction(()=>{db.prepare('UPDATE replacements SET status=? WHERE id=?').run(accept?'accepted':'rejected',replacement.id);if(accept)db.prepare('UPDATE order_items SET dish_id=?,price=?,variant=?,addons=? WHERE id=?').run(replacement.proposed_dish_id,replacement.price,replacement.variant,'[]',replacement.order_item_id)});notify(replacement.cook_id,'orders',accept?'Замена принята':'Замена отклонена',replacement.order_item_id);res.json({ok:true})});

  app.post('/api/payments',auth,(req,res)=>{const creditor=one('SELECT * FROM users WHERE id!=?',req.user.id),amount=Number(req.body.amount);if(!creditor||!Number.isInteger(amount)||amount<1||!one('SELECT id FROM currencies WHERE id=?',req.body.currency_id))return res.status(400).json({error:'Проверьте сумму и валюту'});const result=db.prepare('INSERT INTO ledger(debtor_id,creditor_id,currency_id,amount,kind,note,confirmed) VALUES(?,?,?,?,?,?,0)').run(req.user.id,creditor.id,req.body.currency_id,-amount,'payment',String(req.body.note||'').slice(0,300));notify(creditor.id,'debts','Оплата ждёт подтверждения',Number(result.lastInsertRowid));emit([req.user.id]);res.json({ok:true})});
  app.post('/api/payments/:id/confirm',auth,(req,res)=>{const payment=one('SELECT * FROM ledger WHERE id=? AND confirmed=0',req.params.id);if(!payment||payment.creditor_id!==req.user.id)return res.status(403).json({error:'Платёж не найден'});db.prepare('UPDATE ledger SET confirmed=1 WHERE id=?').run(payment.id);notify(payment.debtor_id,'debts','Оплата подтверждена',payment.id);emit([req.user.id]);res.json({ok:true})});
}
