import {isCookAvailable,normalizeQuantity} from './domain.mjs';

export function registerKitchen({app,db,auth,one,q,transaction,telegram}) {
  const column=(table,name,definition)=>{if(!q('PRAGMA table_info('+table+')').some(c=>c.name===name))db.exec('ALTER TABLE '+table+' ADD COLUMN '+name+' '+definition)};
  column('dishes','ingredient_ids',"TEXT DEFAULT '[]'"); column('reviews','image','TEXT'); column('order_items','reason',"TEXT DEFAULT ''"); column('cooks','variants',"TEXT DEFAULT '[]'"); column('order_items','variant','TEXT');
  db.exec("CREATE TABLE IF NOT EXISTS fridge(id INTEGER PRIMARY KEY,name TEXT NOT NULL,quantity REAL NOT NULL DEFAULT 0,unit TEXT NOT NULL DEFAULT 'шт',low_at REAL NOT NULL DEFAULT 1)");
  const wrap=fn=>(req,res)=>Promise.resolve().then(()=>fn(req,res)).catch(e=>{if(!res.headersSent)res.status(400).json({error:e.message})});
  function product(b){const name=String(b.name||'').trim();if(!name)throw Error('Укажите название продукта');const quantity=Number(b.quantity),low=Number(b.low_at);if(!Number.isFinite(quantity)||quantity<0||!Number.isFinite(low)||low<0)throw Error('Количество и порог должны быть неотрицательными');return [name,quantity,String(b.unit||'шт').trim(),low]}
  app.post('/api/fridge',auth,wrap((req,res)=>{const values=product(req.body);if(q('SELECT name FROM fridge').some(p=>p.name.toLocaleLowerCase('ru')===values[0].toLocaleLowerCase('ru')))throw Error('Такой продукт уже есть');res.json({id:Number(db.prepare('INSERT INTO fridge(name,quantity,unit,low_at) VALUES(?,?,?,?)').run(...values).lastInsertRowid)})}));
  app.put('/api/fridge/:id',auth,wrap((req,res)=>{const v=product(req.body);if(q('SELECT id,name FROM fridge').some(p=>p.id!==Number(req.params.id)&&p.name.toLocaleLowerCase('ru')===v[0].toLocaleLowerCase('ru')))throw Error('Такой продукт уже есть');if(!db.prepare('UPDATE fridge SET name=?,quantity=?,unit=?,low_at=? WHERE id=?').run(...v,req.params.id).changes)throw Error('Продукт не найден');res.json({ok:true})}));
  function price(ps){if(!Array.isArray(ps))throw Error('Некорректная цена');for(const p of ps)if(!Number.isInteger(p.amount)||p.amount<1||!one('SELECT id FROM currencies WHERE id=?',p.currency_id))throw Error('Цена должна содержать целые положительные значения');return ps}
  function dish(b){if(!String(b.title||'').trim())throw Error('Укажите название блюда');if(!Number.isInteger(b.minutes)||b.minutes<1)throw Error('Укажите время приготовления');price(b.price);if(!Array.isArray(b.addons))throw Error('Некорректные дополнения');for(const a of b.addons){if(!String(a.name||'').trim())throw Error('Назовите дополнение');if(a.price?.length)price(a.price)}if(new Set(b.addons.map(a=>a.id)).size!==b.addons.length)throw Error('Повтор дополнения');const variants=b.variants||[];if(!Array.isArray(variants))throw Error('Некорректные вариации');for(const v of variants){if(!String(v.name||'').trim())throw Error('Назовите вариацию');if(!v.price?.length)throw Error('Укажите цену вариации');price(v.price)}if(new Set(variants.map(v=>String(v.id))).size!==variants.length)throw Error('Повтор вариации');const ids=b.ingredient_ids||[];if(!Array.isArray(ids)||ids.some(id=>!Number.isInteger(id)||!one('SELECT id FROM fridge WHERE id=?',id)))throw Error('Обновите список ингредиентов');return ids}
  app.post('/api/dishes',auth,wrap((req,res)=>{const b=req.body,ids=dish(b);const id=transaction(()=>{const d=db.prepare('INSERT INTO dishes(title,description,ingredients,category,image,created_by,ingredient_ids) VALUES(?,?,?,?,?,?,?)').run(b.title.trim(),b.description||'',b.ingredients||'',b.category,b.image||null,req.user.id,JSON.stringify(ids));db.prepare('INSERT INTO cooks(dish_id,user_id,price,availability,availability_note,minutes,note,addons,variants) VALUES(?,?,?,?,?,?,?,?,?)').run(d.lastInsertRowid,req.user.id,JSON.stringify(b.price),b.availability||'Доступно',b.availability_note||'',b.minutes,b.note||'',JSON.stringify(b.addons),JSON.stringify(b.variants||[]));return Number(d.lastInsertRowid)});res.json({id})}));
  app.put('/api/dishes/:id',auth,wrap((req,res)=>{if(!one('SELECT id FROM cooks WHERE dish_id=? AND user_id=?',req.params.id,req.user.id))return res.status(403).json({error:'Можно изменять только блюда, которые вы готовите'});const b=req.body,ids=dish(b);transaction(()=>{db.prepare('UPDATE dishes SET title=?,description=?,ingredients=?,category=?,image=?,ingredient_ids=? WHERE id=?').run(b.title.trim(),b.description||'',b.ingredients||'',b.category,b.image||null,JSON.stringify(ids),req.params.id);db.prepare('UPDATE cooks SET price=?,availability=?,availability_note=?,minutes=?,note=?,addons=?,variants=? WHERE dish_id=? AND user_id=?').run(JSON.stringify(b.price),b.availability||'Доступно',b.availability_note||'',b.minutes,b.note||'',JSON.stringify(b.addons),JSON.stringify(b.variants||[]),req.params.id,req.user.id)});res.json({ok:true})}));
  app.post('/api/dishes/:id/join',auth,wrap((req,res)=>{const b=req.body,variants=b.variants||[],addons=b.addons||[];price(b.price||[]);for(const v of variants){if(!String(v.name||'').trim()||!v.price?.length)throw Error('Заполните вариации');price(v.price)}for(const a of addons){if(!String(a.name||'').trim())throw Error('Назовите дополнение');if(a.price?.length)price(a.price)}db.prepare('INSERT OR REPLACE INTO cooks(dish_id,user_id,price,availability,availability_note,minutes,note,addons,variants) VALUES(?,?,?,?,?,?,?,?,?)').run(req.params.id,req.user.id,JSON.stringify(b.price||[]),b.availability||'Доступно',b.availability_note||'',b.minutes||30,b.note||'',JSON.stringify(addons),JSON.stringify(variants));res.json({ok:true})}));
  app.post('/api/orders',auth,wrap(async(req,res)=>{const b=req.body,cook=one('SELECT * FROM users WHERE id!=?',req.user.id);if(!Array.isArray(b.items)||!b.items.length)throw Error('Корзина пуста');const id=transaction(()=>{const o=db.prepare('INSERT INTO orders(customer_id,scheduled_at,comment) VALUES(?,?,?)').run(req.user.id,b.scheduled_at||null,String(b.comment||'').slice(0,500));for(const x of b.items){const c=one('SELECT * FROM cooks WHERE dish_id=? AND user_id=?',x.dish_id,cook.id);if(!c)throw Error('Блюдо больше недоступно');if(!isCookAvailable(c,b.scheduled_at))throw Error('Одно из блюд сейчас недоступно — обновите меню');const variants=JSON.parse(c.variants||'[]'),variant=variants.find(v=>String(v.id)===String(x.variantId));if(variants.length&&!variant)throw Error('Выберите вариацию блюда');const requested=[...new Set(x.addonIds||[])],available=JSON.parse(c.addons||'[]'),selected=available.filter(a=>requested.some(id=>String(id)===String(a.id)));if(selected.length!==requested.length)throw Error('Одно из дополнений больше недоступно');const quantity=normalizeQuantity(x.quantity);const fixedPrice=variant?.price||JSON.parse(c.price||'[]');db.prepare('INSERT INTO order_items(order_id,dish_id,cook_id,price,addons,comment,variant,quantity) VALUES(?,?,?,?,?,?,?,?)').run(o.lastInsertRowid,x.dish_id,cook.id,JSON.stringify(fixedPrice),JSON.stringify(selected),String(x.comment||'').slice(0,500),variant?JSON.stringify({id:variant.id,name:variant.name,price:variant.price}):null,quantity)}return Number(o.lastInsertRowid)});app.locals.notify?.(cook.id,'orders','Новый заказ от '+req.user.name,id);app.locals.emitUpdate?.([req.user.id]);await telegram(cook.telegram_chat,'🍽 Новый заказ от '+req.user.name);res.json({id})}));
  app.patch('/api/order-items/:id/status',auth,wrap((req,res)=>{const i=one('SELECT oi.*,o.customer_id,d.title FROM order_items oi JOIN orders o ON o.id=oi.order_id JOIN dishes d ON d.id=oi.dish_id WHERE oi.id=? AND o.deleted=0',req.params.id);if(!i)throw Error('Заказ не найден');const s=req.body.status,reason=String(req.body.reason||'').trim();if(s==='выполнен'?req.user.id!==i.customer_id:req.user.id!==i.cook_id)return res.status(403).json({error:'Это действие доступно другому участнику'});if(i.status===s)return res.json({ok:true});const allowed={новый:['принят','отклонён'],принят:['готовится','отменён'],готовится:['готов','отменён'],готов:['выполнен','отменён']};if(!allowed[i.status]?.includes(s))throw Error('Статус уже изменился. Обновите заказ');if(['отклонён','отменён'].includes(s)&&!reason)throw Error('Укажите причину отмены');transaction(()=>{db.prepare('UPDATE order_items SET status=?,reason=?,cancel_requested=0 WHERE id=?').run(s,reason,i.id);if(s==='выполнен'){const ps=[...JSON.parse(i.price||'[]'),...JSON.parse(i.addons||'[]').flatMap(a=>a.price||[])];for(const p of ps)db.prepare('INSERT INTO ledger(debtor_id,creditor_id,currency_id,amount,kind,ref_id,note) VALUES(?,?,?,?,?,?,?)').run(i.customer_id,i.cook_id,p.currency_id,p.amount*Math.max(1,i.quantity||1),'order',i.id,i.title)}});const target=req.user.id===i.customer_id?i.cook_id:i.customer_id;app.locals.notify?.(target,s==='выполнен'?'debts':'orders',i.title+': '+s,i.id);app.locals.emitUpdate?.([req.user.id]);const recipient=one('SELECT telegram_chat FROM users WHERE id=?',target);void telegram(recipient?.telegram_chat,i.title+': '+s+(reason?'\nПричина: '+reason:''));res.json({ok:true})}));
  app.post('/api/order-items/:id/cancel',auth,wrap((req,res)=>{const i=one('SELECT oi.*,o.customer_id FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.id=? AND o.deleted=0',req.params.id);if(!i||i.customer_id!==req.user.id)return res.status(403).json({error:'Это не ваш заказ'});if(!['новый','принят','готовится','готов'].includes(i.status))throw Error('Заказ уже завершён');db.prepare('UPDATE order_items SET cancel_requested=1 WHERE id=?').run(i.id);app.locals.notify?.(i.cook_id,'orders','Запрос на отмену заказа',i.id);app.locals.emitUpdate?.([req.user.id]);res.json({ok:true})}));
  app.post('/api/order-items/:id/keep',auth,wrap((req,res)=>{db.prepare('UPDATE order_items SET cancel_requested=0 WHERE id=? AND cook_id=?').run(req.params.id,req.user.id);res.json({ok:true})}));
  app.post('/api/reviews',auth,wrap((req,res)=>{const b=req.body,i=one('SELECT oi.*,o.customer_id FROM order_items oi JOIN orders o ON o.id=oi.order_id WHERE oi.id=? AND o.deleted=0',b.order_item_id);if(!i||i.customer_id!==req.user.id||i.status!=='выполнен')throw Error('Отзыв доступен после получения блюда');if(!Number.isInteger(b.rating)||b.rating<1||b.rating>5)throw Error('Выберите от 1 до 5 звёзд');if(b.image&&!/^\/uploads\/[a-zA-Z0-9_.-]+$/.test(b.image))throw Error('Загрузите фотографию через приложение');db.prepare('INSERT INTO reviews(order_item_id,author_id,cook_id,dish_id,rating,text,image) VALUES(?,?,?,?,?,?,?) ON CONFLICT(order_item_id) DO UPDATE SET rating=excluded.rating,text=excluded.text,image=excluded.image,created_at=CURRENT_TIMESTAMP').run(i.id,req.user.id,i.cook_id,i.dish_id,b.rating,String(b.text||'').trim().slice(0,500),b.image||null);app.locals.notify?.(i.cook_id,'reviews','Новый отзыв на блюдо',i.id);app.locals.emitUpdate?.([req.user.id]);res.json({ok:true})}));
}
