import {useMemo,useState} from 'react';
import {Clock,Heart,Minus,Plus,ReceiptText,Star,X} from 'lucide-react';
import {api,cost,Modal} from './App';
import {KitchenDish} from './Kitchen';

const reviewsFor=(reviews:any[],dishId:number,cookId:number)=>reviews.filter(r=>r.dish_id===dishId&&r.cook_id===cookId);
const average=(reviews:any[])=>reviews.length?(reviews.reduce((sum,r)=>sum+r.rating,0)/reviews.length).toFixed(1).replace('.',','):'0,0';
const cookCost=(cook:any,currencies:any[])=>cook?.variants?.length?'от '+cost(cook.variants[0].price,currencies):cost(cook?.price,currencies);
const available=(cook:any)=>cook.availability==='Доступно'||(cook.availability==='Только по выходным'&&[0,6].includes(new Date().getDay()));

export function MenuExperience({me,data,load,flash,add}:any){
  const [cat,setCat]=useState('Все'),[sort,setSort]=useState('new'),[favoritesOnly,setFavoritesOnly]=useState(false),[detail,setDetail]=useState<any>(),[configure,setConfigure]=useState<any>(),[cart,setCart]=useState<any[]>([]),[editing,setEditing]=useState<any>(),[reviewDish,setReviewDish]=useState<any>();
  const visible=data.dishes.filter((dish:any)=>dish.cooks.some((cook:any)=>cook.user_id!==me.id));
  const cats=['Все',...(data.categories||[]).filter((c:any)=>c.active&&visible.some((d:any)=>d.category===c.name)).map((c:any)=>c.name)];
  const list=useMemo(()=>visible.filter((dish:any)=>(cat==='Все'||dish.category===cat)&&(!favoritesOnly||data.favoriteIds?.includes(dish.id))).sort((a:any,b:any)=>{
    const ca=a.cooks.find((x:any)=>x.user_id!==me.id),cb=b.cooks.find((x:any)=>x.user_id!==me.id);
    if(sort==='rating')return Number(average(reviewsFor(data.reviews,b.id,cb.user_id)).replace(',','.'))-Number(average(reviewsFor(data.reviews,a.id,ca.user_id)).replace(',','.'));
    if(sort==='time')return ca.minutes-cb.minutes;
    if(sort==='popular')return (data.popular?.[b.id]||0)-(data.popular?.[a.id]||0);
    return String(b.created_at).localeCompare(String(a.created_at));
  }),[visible,cat,favoritesOnly,sort,data.reviews,data.favoriteIds,data.popular]);
  const mine=data.dishes.filter((dish:any)=>dish.cooks.some((cook:any)=>cook.user_id===me.id));
  async function favorite(dish:any){const active=!data.favoriteIds?.includes(dish.id);await api('/favorites/'+dish.id,{method:'PUT',body:JSON.stringify({active})});await load();flash(active?'Добавлено в любимые':'Убрано из любимых')}
  async function removeDish(dish:any){const shared=dish.cooks.length>1;if(!confirm(shared?'Перестать готовить «'+dish.title+'»?':'Удалить «'+dish.title+'» полностью?'))return;await api('/dishes/'+dish.id+'/leave',{method:'DELETE'});await load();flash(shared?'Вы больше не готовите это блюдо':'Блюдо удалено')}
  return <>
    <section className="welcome"><p>Добрый день, {me.name}</p><h2>Чего хочется сегодня?</h2></section>
    <div className="menu-toolbar"><div className="categories">{cats.map(name=><button key={name} className={cat===name?'active':''} onClick={()=>setCat(name)}>{name}</button>)}</div><div className="menu-tools"><button className={favoritesOnly?'soft active':'soft'} onClick={()=>setFavoritesOnly(!favoritesOnly)}><Heart fill={favoritesOnly?'currentColor':'none'}/> Любимые</button><label>Сортировка<select value={sort} onChange={e=>setSort(e.target.value)}><option value="new">Сначала новые</option><option value="rating">По рейтингу</option><option value="popular">По популярности</option><option value="time">Быстрее готовятся</option></select></label></div></div>
    <div className="section-title"><h3>Меню для вас</h3><button onClick={add}><Plus/> Добавить</button></div>
    {!list.length?<div className="empty"><span>🍽️</span><p>{favoritesOnly?'В любимых пока пусто. Нажмите сердечко на блюде.':'В этой категории пока нет блюд.'}</p></div>:<div className="dish-grid">{list.map((dish:any)=>{const cook=dish.cooks.find((x:any)=>x.user_id!==me.id),reviews=reviewsFor(data.reviews,dish.id,cook.user_id),fav=data.favoriteIds?.includes(dish.id);return <article className="dish dish-card" key={dish.id}><button className="favorite-button" aria-label={fav?'Убрать из любимых':'Добавить в любимые'} onClick={()=>favorite(dish)}><Heart fill={fav?'currentColor':'none'}/></button><button className="dish-open" onClick={()=>setDetail({d:dish,c:cook})}><div className="photo">{dish.image?<img src={dish.image} alt={dish.title}/>:<span>🍽️</span>}<i>{cook.availability}</i></div><div><small>{dish.category} · от {cook.name}</small><h3>{dish.title}</h3><p><Clock/> {cook.minutes} мин · {cook.name}</p><span className="rating-mini"><Star fill="currentColor"/> {average(reviews)}/5 <small>({reviews.length})</small></span><strong>{cookCost(cook,data.currencies)}</strong></div></button><button className="card-order" disabled={!available(cook)} onClick={()=>setConfigure({d:dish,c:cook})}>{available(cook)?'Выбрать':'Сейчас недоступно'}</button></article>})}</div>}
    {mine.length>0&&<section className="my-dishes"><div className="section-title"><h3>Я готовлю</h3><small>{mine.length}</small></div><div className="manage-list">{mine.map((dish:any)=>{const cook=dish.cooks.find((x:any)=>x.user_id===me.id),reviews=reviewsFor(data.reviews,dish.id,me.id);return <article key={dish.id}><div className="manage-photo">{dish.image?<img src={dish.image} alt={dish.title}/>:<span>🍽️</span>}</div><div><b>{dish.title}</b><small>{cookCost(cook,data.currencies)} · {cook.minutes} мин</small><small className="rating-mini"><Star fill="currentColor"/> {average(reviews)}/5 · {reviews.length}</small><button type="button" className="edit-dish" onClick={()=>setEditing(dish)}>Изменить блюдо</button><button type="button" className="edit-dish" onClick={()=>setReviewDish(dish)}>Отзывы</button></div><button aria-label={'Удалить '+dish.title} onClick={()=>removeDish(dish)}><X/></button></article>})}</div></section>}
    {detail&&<DishDetails item={detail} data={data} close={()=>setDetail(null)} order={()=>{setConfigure(detail);setDetail(null)}}/>}
    {configure&&<Configure item={configure} currencies={data.currencies} close={()=>setConfigure(null)} choose={(item:any)=>{setCart([...cart,item]);setConfigure(null);flash('Добавлено в заказ')}}/>}
    {editing&&<KitchenDish me={me} data={data} load={load} flash={flash} existing={editing} close={()=>setEditing(null)}/>}
    {reviewDish&&<ReviewsModal dish={reviewDish} cookId={me.id} reviews={data.reviews} close={()=>setReviewDish(null)}/>}
    {!!cart.length&&<Cart items={cart} set={setCart} currencies={data.currencies} sent={async payload=>{await api('/orders',{method:'POST',body:JSON.stringify(payload)});setCart([]);await load();flash('Заказ отправлен 💌')}}/>}
  </>
}

function DishDetails({item,data,close,order}:any){const [rating,setRating]=useState(0),[photo,setPhoto]=useState<string|null>(null),reviews=reviewsFor(data.reviews,item.d.id,item.c.user_id).filter((r:any)=>!rating||r.rating===rating);const fridgeNames=JSON.parse(item.d.ingredient_ids||'[]').map((id:number)=>data.fridge.find((p:any)=>p.id===id)?.name).filter(Boolean);return <Modal close={close}><div className="dish-detail">{item.d.image&&<button className="detail-photo" onClick={()=>setPhoto(item.d.image)}><img src={item.d.image} alt={item.d.title}/></button>}<small>{item.d.category} · готовит {item.c.name}</small><h2>{item.d.title}</h2>{item.d.description&&<p>{item.d.description}</p>}<div className="detail-facts"><span><Clock/> {item.c.minutes} минут</span><span className={available(item.c)?'available':'unavailable'}>{item.c.availability}</span></div>{item.c.availability_note&&<p className="order-note">{item.c.availability_note}</p>}<section className="dish-composition"><h3>Состав</h3><p>{[...fridgeNames,item.d.ingredients].filter(Boolean).join(', ')||'Состав не указан'}</p></section>{item.c.note&&<section><h3>От повара</h3><p>{item.c.note}</p></section>}<section><h3>Отзывы · {average(reviewsFor(data.reviews,item.d.id,item.c.user_id))}/5</h3><div className="rating-filter"><button className={!rating?'active':''} onClick={()=>setRating(0)}>Все</button>{[5,4,3,2,1].map(n=><button key={n} className={rating===n?'active':''} onClick={()=>setRating(n)}>{n}★</button>)}</div>{!reviews.length?<p className="muted">Отзывов с такой оценкой нет.</p>:reviews.map((review:any)=><article className="review-card" key={review.id}><b>{'★'.repeat(review.rating)}{'☆'.repeat(5-review.rating)}</b>{review.text&&<p>{review.text}</p>}{review.image&&<button className="review-photo-button" onClick={()=>setPhoto(review.image)}><img className="review-photo" src={review.image} alt="Фото из отзыва"/></button>}<small>{review.author_name}</small></article>)}</section><button className="primary" disabled={!available(item.c)} onClick={order}>{available(item.c)?'Настроить заказ':'Сейчас заказать нельзя'}</button></div>{photo&&<PhotoViewer src={photo} close={()=>setPhoto(null)}/>}</Modal>}

function Configure({item,currencies,close,choose}:any){const variants=item.c.variants||[],addons=item.c.addons||[];const [variantId,setVariantId]=useState<any>(variants[0]?.id??null),[addonIds,setAddonIds]=useState<any[]>([]),[comment,setComment]=useState('');const variant=variants.find((x:any)=>String(x.id)===String(variantId)),base=variant?.price||item.c.price,total=[...base,...addons.filter((a:any)=>addonIds.includes(a.id)).flatMap((a:any)=>a.price||[])];return <Modal close={close}><h2>{item.d.title}</h2>{variants.length>0&&<fieldset className="variant-picker"><legend>Выберите вариант</legend>{variants.map((v:any)=><label key={v.id} className={String(v.id)===String(variantId)?'selected':''}><input type="radio" name="variant" checked={String(v.id)===String(variantId)} onChange={()=>setVariantId(v.id)}/><span>{v.name}</span><b>{cost(v.price,currencies)}</b></label>)}</fieldset>}{addons.length>0&&<fieldset><legend>Дополнения</legend>{addons.map((addon:any)=><label className="check" key={addon.id}><input type="checkbox" checked={addonIds.includes(addon.id)} onChange={e=>setAddonIds(e.target.checked?[...addonIds,addon.id]:addonIds.filter(id=>id!==addon.id))}/><span>{addon.name}</span><b>{addon.price?.length?cost(addon.price,currencies):'Бесплатно'}</b></label>)}</fieldset>}<label>Комментарий<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Например, без лука" maxLength={500}/></label><div className="config-total"><span>За порцию</span><b>{cost(total,currencies)}</b></div><button className="primary" onClick={()=>choose({dish_id:item.d.id,title:item.d.title,image:item.d.image,variantId:variant?.id,variantName:variant?.name,addonIds,addonNames:addons.filter((a:any)=>addonIds.includes(a.id)).map((a:any)=>a.name),comment,price:total,quantity:1})}>Добавить в заказ</button></Modal>}

function Cart({items,set,currencies,sent}:any){const [open,setOpen]=useState(false),[when,setWhen]=useState(''),[comment,setComment]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const count=items.reduce((n:any,x:any)=>n+x.quantity,0);const totals=new Map<number,number>();items.forEach(item=>item.price.forEach((p:any)=>totals.set(+p.currency_id,(totals.get(+p.currency_id)||0)+p.amount*item.quantity)));const totalPrices=[...totals].map(([currency_id,amount])=>({currency_id,amount}));function quantity(index:number,value:number){set(items.map((item:any,i:number)=>i===index?{...item,quantity:Math.max(1,Math.min(20,value))}:item))}async function send(){setBusy(true);setError('');try{await sent({items,scheduled_at:when||null,comment});setOpen(false)}catch(e:any){setError(e.message)}finally{setBusy(false)}}return <><button className="cart" onClick={()=>setOpen(true)}><ReceiptText/><b>{count}</b> Корзина · {cost(totalPrices,currencies)}</button>{open&&<Modal close={()=>setOpen(false)}><h2>Ваш заказ</h2><div className="cart-list">{items.map((item:any,index:number)=><article className="cart-row improved" key={index}>{item.image&&<img src={item.image} alt=""/>}<span><b>{item.title}{item.variantName&&<em> · {item.variantName}</em>}</b>{item.addonNames?.length>0&&<small>{item.addonNames.join(', ')}</small>}<small>{cost(item.price,currencies)} за порцию</small></span><div className="quantity"><button onClick={()=>quantity(index,item.quantity-1)}><Minus/></button><b>{item.quantity}</b><button onClick={()=>quantity(index,item.quantity+1)}><Plus/></button></div><button className="remove-cart" aria-label="Убрать" onClick={()=>set(items.filter((_:any,i:number)=>i!==index))}><X/></button></article>)}</div><div className="cart-total"><span>Итого</span><b>{cost(totalPrices,currencies)}</b></div><label>Когда приготовить<input type="datetime-local" value={when} onChange={e=>setWhen(e.target.value)}/></label><label>Общий комментарий<textarea value={comment} onChange={e=>setComment(e.target.value)} maxLength={500}/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy} onClick={send}>{busy?'Проверяем доступность…':'Отправить заказ'}</button></Modal>}</>}

function ReviewsModal({dish,cookId,reviews,close}:any){const [rating,setRating]=useState(0),[photo,setPhoto]=useState<string|null>(null);const all=reviewsFor(reviews,dish.id,cookId),list=all.filter((r:any)=>!rating||r.rating===rating);return <Modal close={close}><h2>Отзывы о «{dish.title}»</h2><p className="review-total"><Star fill="currentColor"/> {average(all)}/5 · {all.length}</p><div className="rating-filter"><button className={!rating?'active':''} onClick={()=>setRating(0)}>Все</button>{[5,4,3,2,1].map(n=><button key={n} className={rating===n?'active':''} onClick={()=>setRating(n)}>{n}★</button>)}</div>{!list.length?<p className="empty">Отзывов с такой оценкой пока нет.</p>:<div className="review-list">{list.map((r:any)=><article key={r.id}><b className="stars">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</b>{r.text&&<p>{r.text}</p>}{r.image&&<button className="review-photo-button" onClick={()=>setPhoto(r.image)}><img className="review-photo" src={r.image} alt="Фото из отзыва"/></button>}<small>{r.author_name}</small></article>)}</div>}{photo&&<PhotoViewer src={photo} close={()=>setPhoto(null)}/>}</Modal>}
function PhotoViewer({src,close}:any){return <div className="photo-viewer" role="dialog" aria-label="Просмотр фотографии" onClick={close}><button className="photo-viewer-close" onClick={close}><X/></button><img src={src} alt="Фотография" onClick={e=>e.stopPropagation()}/></div>}
